---
title: "Home"
---

<style>
body {
text-align: justify}
</style>

Material is based on Stanford Probability & Statistics course. More information can be found [here](https://lagunita.stanford.edu/courses/course-v1:OLI+ProbStat+Open_Jan2017/about).

The Probability and Statistics course contains four main units that have several sections within each unit.

* Exploratory Data Analysis: This unit is organized into two sections – Examining Distributions and Examining Relationships. The general approach is to provide participants with a framework that will help them choose the appropriate descriptive methods in various data analysis situations.

* Producing Data: This unit is organized into two sections – Sampling and Designing Studies.

* Probability: In this course the unit is a classical treatment of probability and includes basic probability principles, finding probability of events, conditional probability, discrete random variables (including the Binomial distribution) and continuous random variables (with emphasis on the normal distribution). The probability unit culminates in a discussion of sampling distributions that is grounded in simulation. For a streamlined version of probability that forgoes the classical treatment of probability in favor of an empirical approach using relative frequency, participants may see the OLI Statistical Reasoning course.

* Inference: This unit introduces participants to the logic as well as the technical side of the main forms of inference: point estimation, interval estimation and hypothesis testing. The unit covers inferential methods for the population mean and population proportion, inferential methods for comparing the means of two groups and of more than two groups (ANOVA), the Chi-Square test for independence and linear regression. The unit reinforces the framework that the participants were introduced to in the Exploratory Data Analysis for choosing the appropriate, in this case, inferential method in various data analysis scenarios.

Throughout the course there are many interactive elements. These include: simulations, “walk-throughs” that integrate voice and graphics to explain an example of a procedure or a difficult concept, and, most prominently, interactive activities in which participants practice problem solving, with hints and immediate and targeted feedback.

The course is built around a series of carefully devised learning objectives that are independently assessed.
